### ISSUE TITLE
expression in function body

### ISSUE THREAD

**Issue by knoebber** [alexthemitchell/SOFT#1]
>> function fun(x,y,z){x}
Function "fun" declared with parameters ["z","y","x"]
>> function(x,y,z){x+y}
REPL.hs: Parse Error lol

**Comment by alexthemitchell** [comment]
Confirmed in 90f57be072cd24c4052011af485033490d29814f.
```
>> function test(x,y,z){x+y}
SOFTRun.hs: Parse Error lol
CallStack (from HasCallStack):
  error, called at ./SOFTLexer.hs:6:16 in main:SOFTLexer
```
I thought it may have been because you didn't have a function name, nor a space after the keyword `function`, but it appears to still be a problem.

**Comment by alexthemitchell** [comment]
```
>> function f (x,y,z) { let a = 5 }
Function "f" declared with parameters ["x","y","z"]
>> function f (x,y,z) { x + 1 }
SOFTRun.hs: Parse Error lol
```

I suspect [this line](https://github.com/alexthemitchell/SOFT/blob/master/SOFTGrammar.y#L56) is the culprit.
